name: release

on:
  workflow_dispatch: {}
  push:
    tags:
      - "*"

jobs:
  windows-x64-gpu:
    name: vs2022
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          path: fisher
      - name: cache-opencv-mobile
        id: cache-opencv-mobile
        uses: actions/cache@v3
        with:
          path: opencv-mobile
          key: opencv-mobile-vs2022-v28
      - name: opencv-mobile
        if: steps.cache-opencv-mobile.outputs.cache-hit != 'true'
        run: |
          Invoke-WebRequest -Uri https://github.com/nihui/opencv-mobile/releases/download/v28/opencv-mobile-4.10.0-windows-vs2022.zip -OutFile opencv-mobile-4.10.0-windows-vs2022.zip
          7z x ./opencv-mobile-4.10.0-windows-vs2022.zip
          mv opencv-mobile-4.10.0-windows-vs2022 opencv-mobile
      - name: cache-ncnn
        id: cache-ncnn
        uses: actions/cache@v3
        with:
          path: ncnn
          key: ncnn-windows-vs2022-20240410
      - name: ncnn
        if: steps.cache-ncnn.outputs.cache-hit != 'true'
        run: |
          Invoke-WebRequest -Uri https://github.com/Tencent/ncnn/releases/download/20240410/ncnn-20240410-windows-vs2022.zip -OutFile ncnn-20240410-windows-vs2022.zip
          7z x ./ncnn-20240410-windows-vs2022.zip
          mv ncnn-20240410-windows-vs2022 ncnn
      - name: cache-vulkansdk
        id: cache-vulkansdk
        uses: actions/cache@v3
        with:
          path: VulkanSDK.exe
          key: VulkanSDK-1.3.275.0-Installer
      - name: download-vulkansdk
        if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
        run: |
          Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/1.3.275.0/windows/VulkanSDK-1.3.275.0-Installer.exe?Human=true -OutFile VulkanSDK.exe
      - name: vulkansdk
        run: |
          ./VulkanSDK.exe --accept-licenses --default-answer --confirm-command install
      - name: build
        run: |
          $env:VULKAN_SDK="C:/VulkanSDK/1.3.275.0"
          $env:Path+=";C:/VulkanSDK/1.3.275.0/Bin"
          cd fisher/src
          mkdir build
          cd build
          cmake -DRELEASE=ON ..
          cmake --build . --config Release
      - name: make-archive
        run: |
          cd fisher
          mkdir HutaoFisher
          mv src/build/Release/fisher.exe HutaoFisher
          cp config.json HutaoFisher
          cp help.txt HutaoFisher
          cp -r resource HutaoFisher
          7z a HutaoFisher.zip HutaoFisher
      - name: release
        uses: actions/upload-artifact@v4
        with:
          path: fisher/HutaoFisher.zip
